import { bankaApi } from "./features/banka/bankaApi";
import { bankaSubeApi } from "./features/bankaSube/bankaSubeApi";
import { beyannameSozlukApi } from "./features/beyanname/beyannameSozlukApi";
import { beyannameTanimApi } from "./features/beyanname/beyannameTanimApi";
import { damgaBeyannameApi } from "./features/beyanname/damgaBeyannameApi";
import { damgaBeyannamePdfApi } from "./features/beyanname/damgaBeyannamePdfApi";
import { kdv1BeyannameApi } from "./features/beyanname/kdv1BeyannameApi";
import { kdv1BeyannamePdfApi } from "./features/beyanname/kdv1BeyannamePdfApi";
import { kdv2BeyannameApi } from "./features/beyanname/kdv2BeyannameApi";
import { kdv2BeyannamePdfApi } from "./features/beyanname/kdv2BeyannamePdfApi";
import { turizmBeyannameApi } from "./features/beyanname/turizmBeyannameApi";
import { turizmBeyannamePdfApi } from "./features/beyanname/turizmBeyannamePdfApi";
import { documentPostingApi } from "./features/document-posting/documentPostingApi";
import { documentApi } from "./features/document/documentApi";
import { donemApi } from "./features/donem/donemApi";
import { duyuruApi } from "./features/duyuru/duyuruApi";
import { entegratorApi } from "./features/entegrator/entegratorApi";
import { fisApi } from "./features/fis/fisApi";
import { gelirApi } from "./features/gelir/gelirApi";
import { giderApi } from "./features/gider/giderApi";
import { hesapPlaniApi } from "./features/hesapplani/hesapPlaniApi";
import { isyeriApi } from "./features/isyeri/isyeriApi";
import { isyeriBolumApi } from "./features/isyeriBolum/isyeriBolumApi";
import { kurApi } from "./features/kur/kurApi";
import { menuApi } from "./features/menu/menuApi";
import { muhasebeTanimApi } from "./features/muhasebeTanim/muhasebeTanimApi";
import { musteriApi } from "./features/musteri/musteriApi";
import { userApi } from "./features/musteri/userApi";
import { personelApi } from "./features/personel/personelApi";
import { personelGirisCikisApi } from "./features/personel/personelGirisCikisApi";
import { reportApi } from "./features/report/reportApi";
import { sabitKiymetApi } from "./features/sabitkiymet/sabitkiymetApi";
import { searchApi } from "./features/search/searchApi";
import { sirketApi } from "./features/sirket/sirketApi";
import { smmBilgileriApi } from "./features/smmBilgileri/smmBilgileriApi";
import { sozlukApi } from "./features/sozluk/sozlukApi";

export const apiRegistry = [
//   sirketApi,
];
